plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.kotlinAndroid)
    alias(libs.plugins.kotlinxSerialization)
    //alias(libs.plugins.kapt)
    alias(libs.plugins.compose.compiler)
    id 'com.google.devtools.ksp'
}

android {
    namespace 'ru.otus.marketsample'
    compileSdk 36

    defaultConfig {
        applicationId "ru.otus.marketsample"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        viewBinding true
        compose = true
    }
}

dependencies {
    def composeBom = libs.androidx.compose.bom
    implementation composeBom
    androidTestImplementation composeBom
    implementation libs.androidx.compose.material3
    implementation("androidx.compose.material:material:1.6.0")
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.tooling.preview
    debugImplementation libs.androidx.compose.ui.tooling
    implementation libs.androidx.activity.compose
    implementation libs.androidx.lifecycle.viewmodel.compose
    implementation libs.coil.compose
    implementation libs.coil.network.okhttp

    implementation project(":common:di")
    implementation project(":common:formatters")
    implementation project(":common:ui")
    implementation project(":common:data:products")
    implementation project(":common:data:promo")

    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.swipetorefresh
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.fragment.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx
    implementation libs.coil
    implementation libs.gson
    implementation libs.bundles.network
    implementation libs.kotlin.serialization
    implementation libs.kotlinx.serializationJson
    implementation libs.androidx.datastore
    implementation libs.androidx.datastore.preferences

    implementation libs.dagger
    ksp libs.daggerCompiler

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.ext.junit
    androidTestImplementation libs.espresso.core
}